Header full width
cyfronet-fid/eosc-portal-common pull request #225
Opened 2023-03-01 18:01 UTC by jarekzet

Make common header 100% layout width

2023-03-02 09:27 UTC, Marcelinna approved these changes

2023-03-02 11:25 UTC, agpul commented
@jarekzet make appropriate changes according to new design agreed on the meeting: https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/Marketplace-EOSC?node-id=1496%3A7157&t=oj5MOb0WyHtHl3O6-0

2023-03-03 10:12 UTC, Marcelinna approved these changes

2023-03-03 11:04 UTC, michal-szostak requested changes

2023-03-03 11:08 UTC, jarekzet commented on configurations/main-header.beta.config.json
> +    "url": "https://marketplace.eosc-portal.eu/"
true, I pushed modification

2023-03-03 12:13 UTC, michal-szostak approved these changes

2023-03-03 12:14 UTC, merged